[package]
name = "game_of_life"
version = "0.1.0"
authors = ["amarrerod <alemarrerodiaz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
rand = "0.8.5"
